### ISSUE TITLE
spotify connect

### ISSUE THREAD

**Issue by dylono96** [pimusicbox/mopidy-websettings#25]
How do i set this up? When i enable it it doesn't do much.

**Comment by kingosticks** [comment]
* Enable it
* Keep the firewall disabled (for now)
* Reboot, you 
* Open your official Spotify client and musicbox should appear as an output device

You obviously require Spotify Premium.

**Comment by dylono96** [comment]
I found it, what you discribed didnt work for me. instead I installed [https://github.com/dtcooper/raspotify](url) and I used that config. but thanks anyway!
