### ISSUE TITLE
Https jquery or local library 

### ISSUE THREAD

**Issue by daverck** [pimusicbox/mopidy-websettings#27]
Hi,

Because websettings use http to link jquery library I can't do a reverse proxy using httpS.
Its no big deal but maybe you should include the library in the next release.

Also if you can point me to a way to proxy websettings (and musibox) in a subdirectory i d like that (eg localhost/admin/mopidy/settings)

**Comment by kingosticks** [comment]
A reverse proxy such as nginx will allow you specify a URL re-write rule. There's something at https://github.com/pimusicbox/pimusicbox/blob/release-1.0/filechanges/etc/nginx/sites-available/musicbox which you might be able to base something off.
