### ISSUE TITLE
Mopidy-Websettings does not appear to be recognised as installed

### ISSUE THREAD

**Issue by NathanielJS1541** [pimusicbox/mopidy-websettings#31]
I am running Mopidy on a Raspberry Pi 3B+ as a service. I installed Mopidy-Websettings using `pip install Mopidy-WebSettings` and the installation appears successful.  
`pip list` confirms that it is installed (Amongst other things):
```
Mopidy (2.2.2)
Mopidy-AudioAddict (0.2.7)
Mopidy-Mopify (1.6.1)
Mopidy-MusicBox-Webclient (2.5.0)
Mopidy-SoundCloud (2.1.0)
Mopidy-Spotify (3.1.0)
Mopidy-Spotify-Tunigo (1.0.0)
Mopidy-WebSettings (0.2.3)
Mopidy-Youtube (2.0.2)
```
In the config file (/etc/mopidy/mopidy.conf) here is how I have configured websettings:
```
[websettings]
enabled = true
musicbox = false
config_file = /etc/mopidy/mopidy.conf
```
But the extension doesn't show up when I go to **http://natspi3musicbox.local:6680/**. If I run `sudo mopidyctl local scan` I get the following output: 
```
Running "/usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf local scan" as user mopidy
INFO     Starting Mopidy 2.2.2
INFO     Loading config from builtin defaults
INFO     Loading config from /etc/mopidy/mopidy.conf
INFO     Loading config from command line options
INFO     Enabled extensions: mopify, spotify, http, stream, spotify_tunigo, softwaremixer, file, musicbox_webclient, local, soundcloud
INFO     Disabled extensions: mpd, m3u
INFO     Found 187 files in media_dir.
INFO     Checking 123 tracks from library.
INFO     Removing 0 missing tracks.
INFO     Found 14 tracks which need to be updated.
INFO     Scanning...
```
What I'm interested in here is the following:
```
INFO     Enabled extensions: mopify, spotify, http, stream, spotify_tunigo, softwaremixer, file, musicbox_webclient, local, soundcloud
INFO     Disabled extensions: mpd, m3u
```
Since it doesn't appear to recognise websettings as either enabled or disabled. Is this a problem with my config file?
This is similar to #26, but in their output of `sudo mopidyctl local scan` they get _websettings_ listed as an enabled extension so I have filed it as a separate issue.
Thanks in advance for your time.

**Comment by kingosticks** [comment]
We use `mopidy deps` to show what Mopidy can "see" installed. If you are running as a service that's `sudo mopidyctl deps`. I imagine it will not show Mopidy-Websettings in the output.

Short answer: install with `sudo pip install Mopidy-Websettings` if you want to use it with Mopidy running as a service. That goes for any Mopidy extension.

Longer answer: at some point in last year or two, pip changed it's behaviour when it's called without `sudo`. It used to try to install into the system-wide directories (and fail with an obvious permission error), but now it just installs into your home directory instead. It sounds like that's what has happened here. The system service doesn't know anything about stuff in user home directories so it won't find any extensions installed in there.

**Comment by NathanielJS1541** [comment]
I can't believe I didn't think of that - sorry! Everything works fine now, thanks very much.
