### ISSUE TITLE
Mopidy wont find Websettings Frontend

### ISSUE THREAD

**Issue by marrobHD** [pimusicbox/mopidy-websettings#32]
Mopidy wont find Websettings Frontend. I have entered that:
```
[websettings]
enabled = true
musicbox = false
config_file = /etc/mopidy/mopidy.conf
```
in both config files the be sure. But no success.
Thats my log:
```
pi@raspberrypi:~/Schreibtisch $ sudo systemctl status mopidy
● mopidy.service - Mopidy music server
   Loaded: loaded (/lib/systemd/system/mopidy.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2019-05-21 17:55:18 CEST; 7min ago
  Process: 3602 ExecStartPre=/bin/chown mopidy:audio /var/cache/mopidy (code=exited, status=0/SUCCESS)
  Process: 3599 ExecStartPre=/bin/mkdir -p /var/cache/mopidy (code=exited, status=0/SUCCESS)
 Main PID: 3605 (mopidy)
   CGroup: /system.slice/mopidy.service
           └─3605 /usr/bin/python /usr/bin/mopidy --config /usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf

Mai 21 17:55:22 raspberrypi mopidy[3605]: INFO     Loaded 874 local tracks using sqlite
Mai 21 17:55:22 raspberrypi mopidy[3605]: INFO     Logged in to Spotify in offline mode
Mai 21 17:55:22 raspberrypi mopidy[3605]: INFO     Logged in to SoundCloud as "TEST User"
Mai 21 17:55:22 raspberrypi mopidy[3605]: INFO     Starting Mopidy core
Mai 21 17:55:23 raspberrypi mopidy[3605]: INFO     Starting Mopidy frontends: IrisFrontend, MpdFrontend, HttpFrontend
Mai 21 17:55:23 raspberrypi mopidy[3605]: INFO     Starting Iris 3.37.1
Mai 21 17:55:23 raspberrypi mopidy[3605]: INFO     MPD server running at [::ffff:127.0.0.1]:6600
Mai 21 17:55:23 raspberrypi mopidy[3605]: INFO     Starting GLib mainloop
Mai 21 17:55:23 raspberrypi mopidy[3605]: INFO     HTTP server running at [::]:6680
Mai 21 17:55:23 raspberrypi mopidy[3605]: INFO     Logged in to Spotify in online mode

```
Thanks for help

**Comment by kingosticks** [comment]
Do you see mopidy-websettings in the output of `sudo mopidyctl deps`? I am going to guess not.

If you are running Mopidy as a service you need to install the extension with `sudo pip install mopidy-websettings` so that the extension is installed outside of the `pi` users home directory and in a place that the service user (`mopidy`) can find it.

**Comment by kingosticks** [comment]
I've updated the README to reflect this requirement (pip changed it's behaviour at some point).

**Comment by marrobHD** [comment]
I have tried both with and without sudo. Same issue

**Comment by kingosticks** [comment]
Please provide the output of `sudo mopidyctl deps`, `sudo mopidyctl config`, and also `sudo pip show mopidy-websettings`.

**Comment by marrobHD** [comment]
sudo mopidyctl deps: https://hastebin.com/huxoxutece.js
sudo mopidyctl config: https://hastebin.com/ucesicoxuc.makefile
sudo pip show mopidy-websettings: https://hastebin.com/soromipere.http

**Comment by kingosticks** [comment]
Those links don't seem to contain anything. If you could also check your log, the first few lines will display what extensions are enabled:
> INFO     Starting Mopidy 2.2.2-52-g06ce529a
INFO     Loading config from builtin defaults
INFO     Loading config from /home/nick/.config/mopidy/mopidy.conf
INFO     Loading config from command line options
INFO     Enabled extensions: spotify, mpd, http, stream, m3u, tunein, softwaremixer, file, musicbox_webclient, websettings, local, local-sqlite, soundcloud
INFO     Disabled extensions: mpris
INFO     Starting Mopidy audio
INFO     Starting Mopidy backends: StreamBackend, M3UBackend, FileBackend, LocalBackend, SpotifyBackend, TuneInBackend, SoundCloudBackend
INFO     Audio output set to "autoaudiosink"
INFO     Loaded 98 local tracks using sqlite

**Comment by marrobHD** [comment]
Mai 23 23:34:18 raspberrypi mopidy[523]: First error at line 27.
Mai 23 23:34:18 raspberrypi mopidy[523]: ERROR    Uncaught exception GET /settings/ (192.168.178.39)
Mai 23 23:34:18 raspberrypi mopidy[523]: HTTPServerRequest(protocol='http', host='192.168.178.66:6680', method='GET', uri='/settings/', version='HTTP/1.1', remote_ip='192.168.178.39', headers={'Accept-Language': 'de-DE,de;q=0.9,en-US;q=0
Mai 23 23:34:18 raspberrypi mopidy[523]: Traceback (most recent call last):
Mai 23 23:34:18 raspberrypi mopidy[523]:   File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1510, in _execute
Mai 23 23:34:18 raspberrypi mopidy[523]:     result = method(*self.path_args, **self.path_kwargs)
Mai 23 23:34:18 raspberrypi mopidy[523]:   File "/usr/local/lib/python2.7/dist-packages/mopidy_websettings/__init__.py", line 95, in get
Mai 23 23:34:18 raspberrypi mopidy[523]:     configValue = iniconfig.get(item, {}).get(subitem, None)
Mai 23 23:34:18 raspberrypi mopidy[523]: UnboundLocalError: local variable 'iniconfig' referenced before assignment
Mai 23 23:34:18 raspberrypi mopidy[523]: ERROR    500 GET /settings/ (192.168.178.39) 691.57ms

**Comment by kingosticks** [comment]
I should have asked for the log initially rather than trust that snippet. When will I learn. 

Did you leave out the first interesting line where it says "Could not load ini file!" ? And is line 27 of your config file a list item? If so, this sounds just like https://github.com/pimusicbox/mopidy-websettings/issues/29

**Comment by marrobHD** [comment]
I  coudnt find anything. Thats my config: https://pastebin.com/rfxjZQNJ

**Comment by kingosticks** [comment]
That looks to me like the output of `sudo mopidyctl config` rather the actual contents of the file at  /etc/mopidy/mopidy.conf that mopidy-websettings is trying to read. Specicaly line 27 of that file.

**Comment by marrobHD** [comment]
That is the line 27 https://i.imgur.com/Pvlbkky.png

**Comment by kingosticks** [comment]
Yes, and look, it's a list item, just like in #29 ...

Either delete lines 26 to 28 since you don't need settings in your config file for which you are keeping the default values. As per https://docs.mopidy.com/en/latest/config/:
 > If you want to keep the default for a config value, you should not add it to the config file, but leave it out so that when we change the default value in a future version, you won’t have to change your configuration accordingly.

Or change it to:
```
command_blacklist = listall, listallinfo
```

**Comment by marrobHD** [comment]
Thanks :)
